export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const ENTER_FULLSCREEN = 'ENTER_FULLSCREEN';
export const EXIT_FULLSCREEN = 'EXIT_FULLSCREEN';
export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';
export const CHANGE_REQUEST_FIELD_SIZE = 'CHANGE_REQUEST_FIELD_SIZE';


